//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD.WebTests {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    
    
    public class WebTest1Coded : WebTest {
        
        public WebTest1Coded() {
            this.Context.Add("WebServer1", "http://api.bing.com");
            this.Context.Add("WebServer2", "http%3A%2F%2Flocalhost%3A8516");
            this.Context.Add("WebServer3", "http://localhost:8516");
            this.Context.Add("WebServer4", "http://localhost:28750");
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }
        
        public override IEnumerator<WebTestRequest> GetRequestEnumerator() {
            // Initialiser les règles de validation qui s'appliquent à toutes les requêtes dans le test Web
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest((this.Context["WebServer1"].ToString() + "/qsml.aspx"));
            request1.ThinkTime = 1;
            request1.QueryStringParameters.Add("query", (this.Context["WebServer2"].ToString() + "%2F"), false, false);
            request1.QueryStringParameters.Add("src", "IE-Address", false, false);
            request1.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request1.QueryStringParameters.Add("rowheight", "20", false, false);
            request1.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request1.QueryStringParameters.Add("FORM", "IE8SSC", false, false);
            request1.QueryStringParameters.Add("market", "fr-FR", false, false);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/"));
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/negotiate"));
            request3.ThinkTime = 4;
            request3.Method = "POST";
            request3.Headers.Add(new WebTestRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8"));
            request3.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request3.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            request3.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2F"), false, false);
            request3.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request3.QueryStringParameters.Add("clientProtocol", "1.3", false, false);
            request3.QueryStringParameters.Add("_", "1425043897515", false, false);
            FormPostHttpBody request3Body = new FormPostHttpBody();
            request3.Body = request3Body;
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/"));
            request4.Method = "POST";
            request4.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            FormPostHttpBody request4Body = new FormPostHttpBody();
            request4Body.FormPostParameters.Add("SearchText", "tdd");
            request4.Body = request4Body;
            WebTestRequest request4Dependent1 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/abort"));
            request4Dependent1.Method = "POST";
            request4Dependent1.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request4Dependent1.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            request4Dependent1.QueryStringParameters.Add("transport", "webSockets", false, false);
            request4Dependent1.QueryStringParameters.Add("connectionToken", @"AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAS27WNAsUXUK97ET%2FNLI%2F6QAAAAACAAAAAAAQZgAAAAEAACAAAADW19asX69kJkkhIOVikztRQIGnAuzabMuT3bL%2FPq6srwAAAAAOgAAAAAIAACAAAACIdDl%2FKSqRfwqPbLLffX92uBv9jLmY8GLxAOaxZfo8uTAAAAC7dfP%2FXXQJzcdmcMaovrsi3kLBXBRSuvIwoYmNNaLRpIHnED7Ujv7GF1q0tAwqJ1BAAAAA0P8Gv4teKK8WhMhi7KdmSr2b6zd%2Byb3SPqKiIhjmgWD0%2Be7MhpKLCXMRRo9M4j04gJ%2BL%2FpLLN1cDbstQE7VAYg%3D%3D", false, false);
            request4Dependent1.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2F"), false, false);
            request4Dependent1.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            FormPostHttpBody request4Dependent1Body = new FormPostHttpBody();
            request4Dependent1.Body = request4Dependent1Body;
            request4.DependentRequests.Add(request4Dependent1);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/connect"));
            request5.QueryStringParameters.Add("transport", "webSockets", false, false);
            request5.QueryStringParameters.Add("connectionToken", @"AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAS27WNAsUXUK97ET%2FNLI%2F6QAAAAACAAAAAAAQZgAAAAEAACAAAADW19asX69kJkkhIOVikztRQIGnAuzabMuT3bL%2FPq6srwAAAAAOgAAAAAIAACAAAACIdDl%2FKSqRfwqPbLLffX92uBv9jLmY8GLxAOaxZfo8uTAAAAC7dfP%2FXXQJzcdmcMaovrsi3kLBXBRSuvIwoYmNNaLRpIHnED7Ujv7GF1q0tAwqJ1BAAAAA0P8Gv4teKK8WhMhi7KdmSr2b6zd%2Byb3SPqKiIhjmgWD0%2Be7MhpKLCXMRRo9M4j04gJ%2BL%2FpLLN1cDbstQE7VAYg%3D%3D", false, false);
            request5.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2F"), false, false);
            request5.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request5.QueryStringParameters.Add("tid", "8", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/__browserLink/requestData/c4080a49c9a248c698bdd6f61e8e23c8"));
            request6.ThinkTime = 4;
            request6.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request6.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request6.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/negotiate"));
            request7.ThinkTime = 5;
            request7.Method = "POST";
            request7.Headers.Add(new WebTestRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8"));
            request7.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request7.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            request7.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2F"), false, false);
            request7.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request7.QueryStringParameters.Add("clientProtocol", "1.3", false, false);
            request7.QueryStringParameters.Add("_", "1425043902197", false, false);
            FormPostHttpBody request7Body = new FormPostHttpBody();
            request7.Body = request7Body;
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/Home/About"));
            request8.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/connect"));
            request9.QueryStringParameters.Add("transport", "webSockets", false, false);
            request9.QueryStringParameters.Add("connectionToken", @"AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAS27WNAsUXUK97ET%2FNLI%2F6QAAAAACAAAAAAAQZgAAAAEAACAAAABDzEZh7Bf%2Fq%2FOFOLS9HU3cHoiG4jYDpwRS%2BPGlvhKQTAAAAAAOgAAAAAIAACAAAABjuFr%2BSbmWdi4GOVPkkfGz59ezl3EFcIwne4OuUrIoGDAAAADzpJuAmkl3I7%2BfnvWpu%2FKPOwxJux%2BWo8uKRWl45Oa3Q5MPV%2FfUw9I6QDwbx2E7x6NAAAAACqZOCR3W%2FGxLYzAgo2dxRraccZUj%2Bcju2RHpYIPRpwFzyE3a0W29ou92%2F2NFUsy3M0Q7wXxSUrcUd7UeLxKu8g%3D%3D", false, false);
            request9.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2F"), false, false);
            request9.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request9.QueryStringParameters.Add("tid", "8", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/__browserLink/requestData/6c6f95e408de45c5a906a266ae989648"));
            request10.ThinkTime = 5;
            request10.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request10.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request10.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/abort"));
            request11.Method = "POST";
            request11.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request11.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            request11.QueryStringParameters.Add("transport", "webSockets", false, false);
            request11.QueryStringParameters.Add("connectionToken", @"AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAS27WNAsUXUK97ET%2FNLI%2F6QAAAAACAAAAAAAQZgAAAAEAACAAAABDzEZh7Bf%2Fq%2FOFOLS9HU3cHoiG4jYDpwRS%2BPGlvhKQTAAAAAAOgAAAAAIAACAAAABjuFr%2BSbmWdi4GOVPkkfGz59ezl3EFcIwne4OuUrIoGDAAAADzpJuAmkl3I7%2BfnvWpu%2FKPOwxJux%2BWo8uKRWl45Oa3Q5MPV%2FfUw9I6QDwbx2E7x6NAAAAACqZOCR3W%2FGxLYzAgo2dxRraccZUj%2Bcju2RHpYIPRpwFzyE3a0W29ou92%2F2NFUsy3M0Q7wXxSUrcUd7UeLxKu8g%3D%3D", false, false);
            request11.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2F"), false, false);
            request11.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            FormPostHttpBody request11Body = new FormPostHttpBody();
            request11.Body = request11Body;
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/negotiate"));
            request12.ThinkTime = 3;
            request12.Method = "POST";
            request12.Headers.Add(new WebTestRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8"));
            request12.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request12.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/Home/About")));
            request12.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2FHome%2FAbout"), false, false);
            request12.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request12.QueryStringParameters.Add("clientProtocol", "1.3", false, false);
            request12.QueryStringParameters.Add("_", "1425043907635", false, false);
            FormPostHttpBody request12Body = new FormPostHttpBody();
            request12.Body = request12Body;
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/Home/Contact"));
            request13.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/Home/About")));
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/connect"));
            request14.QueryStringParameters.Add("transport", "webSockets", false, false);
            request14.QueryStringParameters.Add("connectionToken", @"AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAS27WNAsUXUK97ET%2FNLI%2F6QAAAAACAAAAAAAQZgAAAAEAACAAAAD7GVruoNjIFaAudieGBVk3pGoSaIHLys1lDhjydsNwhQAAAAAOgAAAAAIAACAAAAAIXO%2Bw7IpylvIcyE6QqyUYU6mEJeQe6aBZp7zysmzKhjAAAACX02nxD6eP4S97S2nOY05YtH%2FIRDa7ACJBSx%2FUktTGP1hJVDBI5ew2jNm6HKkCVvZAAAAABBZsPR45LBsLTK8VljwfwT8jhUTr8llrXGpObzzJOGbKjdo6DWiM%2BuzvjQN3a6NY%2Ffro4hgNrefAM7IaSdAx7w%3D%3D", false, false);
            request14.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2FHome%2FAbout"), false, false);
            request14.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request14.QueryStringParameters.Add("tid", "4", false, false);
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/__browserLink/requestData/a048b10304e84f1ebb4b35fed04a7775"));
            request15.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request15.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request15.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/Home/About")));
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/abort"));
            request16.Method = "POST";
            request16.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request16.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/Home/About")));
            request16.QueryStringParameters.Add("transport", "webSockets", false, false);
            request16.QueryStringParameters.Add("connectionToken", @"AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAS27WNAsUXUK97ET%2FNLI%2F6QAAAAACAAAAAAAQZgAAAAEAACAAAAD7GVruoNjIFaAudieGBVk3pGoSaIHLys1lDhjydsNwhQAAAAAOgAAAAAIAACAAAAAIXO%2Bw7IpylvIcyE6QqyUYU6mEJeQe6aBZp7zysmzKhjAAAACX02nxD6eP4S97S2nOY05YtH%2FIRDa7ACJBSx%2FUktTGP1hJVDBI5ew2jNm6HKkCVvZAAAAABBZsPR45LBsLTK8VljwfwT8jhUTr8llrXGpObzzJOGbKjdo6DWiM%2BuzvjQN3a6NY%2Ffro4hgNrefAM7IaSdAx7w%3D%3D", false, false);
            request16.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2FHome%2FAbout"), false, false);
            request16.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            FormPostHttpBody request16Body = new FormPostHttpBody();
            request16.Body = request16Body;
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/negotiate"));
            request17.ThinkTime = 1;
            request17.Method = "POST";
            request17.Headers.Add(new WebTestRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8"));
            request17.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request17.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/Home/Contact")));
            request17.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2FHome%2FContact"), false, false);
            request17.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request17.QueryStringParameters.Add("clientProtocol", "1.3", false, false);
            request17.QueryStringParameters.Add("_", "1425043910872", false, false);
            FormPostHttpBody request17Body = new FormPostHttpBody();
            request17.Body = request17Body;
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/"));
            request18.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/Home/Contact")));
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/connect"));
            request19.QueryStringParameters.Add("transport", "webSockets", false, false);
            request19.QueryStringParameters.Add("connectionToken", @"AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAS27WNAsUXUK97ET%2FNLI%2F6QAAAAACAAAAAAAQZgAAAAEAACAAAACHPVPYHn6P%2BkiZLpGHIwgDZ%2FlG1%2BLp4QkJYwUcLq0QzgAAAAAOgAAAAAIAACAAAAAjjw%2FZY6wtXKh1AJlFKTlYlFuciW8GoYaU1AUzgmgJcDAAAAAVkaPiqya%2FDMNcoDtjImA8uXdliXxV8AMdGp8j1BPGgZWBq6PrJxikaoBhsQ4ufnpAAAAA%2FisTpxhMqZCHHcfgC%2BpkyVdZivSGfr4zlHZnlF2xfrnOcrSlzxBqEjc0bfs13R%2FrRJ5cxPgWoRTcgGyZ2pySBg%3D%3D", false, false);
            request19.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2FHome%2FContact"), false, false);
            request19.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request19.QueryStringParameters.Add("tid", "9", false, false);
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/__browserLink/requestData/abf7bee1d5154de3bb92aff7e58acdc0"));
            request20.ThinkTime = 1;
            request20.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request20.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request20.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/Home/Contact")));
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/abort"));
            request21.Method = "POST";
            request21.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request21.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/Home/Contact")));
            request21.QueryStringParameters.Add("transport", "webSockets", false, false);
            request21.QueryStringParameters.Add("connectionToken", @"AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAS27WNAsUXUK97ET%2FNLI%2F6QAAAAACAAAAAAAQZgAAAAEAACAAAACHPVPYHn6P%2BkiZLpGHIwgDZ%2FlG1%2BLp4QkJYwUcLq0QzgAAAAAOgAAAAAIAACAAAAAjjw%2FZY6wtXKh1AJlFKTlYlFuciW8GoYaU1AUzgmgJcDAAAAAVkaPiqya%2FDMNcoDtjImA8uXdliXxV8AMdGp8j1BPGgZWBq6PrJxikaoBhsQ4ufnpAAAAA%2FisTpxhMqZCHHcfgC%2BpkyVdZivSGfr4zlHZnlF2xfrnOcrSlzxBqEjc0bfs13R%2FrRJ5cxPgWoRTcgGyZ2pySBg%3D%3D", false, false);
            request21.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2FHome%2FContact"), false, false);
            request21.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            FormPostHttpBody request21Body = new FormPostHttpBody();
            request21.Body = request21Body;
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest((this.Context["WebServer4"].ToString() + "/623ec47466f64b56bf2b551b8ddbbd7a/arterySignalR/negotiate"));
            request22.Method = "POST";
            request22.Headers.Add(new WebTestRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8"));
            request22.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request22.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            request22.QueryStringParameters.Add("requestUrl", (this.Context["WebServer2"].ToString() + "%2F"), false, false);
            request22.QueryStringParameters.Add("browserName", "InternetExplorer", false, false);
            request22.QueryStringParameters.Add("clientProtocol", "1.3", false, false);
            request22.QueryStringParameters.Add("_", "1425043912317", false, false);
            FormPostHttpBody request22Body = new FormPostHttpBody();
            request22.Body = request22Body;
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest((this.Context["WebServer3"].ToString() + "/__browserLink/requestData/bd902de105904aa3a6217666dad4b096"));
            request23.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request23.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request23.Headers.Add(new WebTestRequestHeader("Referer", (this.Context["WebServer3"].ToString() + "/")));
            yield return request23;
            request23 = null;
        }
    }
}
