// ------------------------------------------------------------------------------
//  <auto-generated>
//      Ce code a été généré par un générateur de test codé de l'interface utilisateur.
//      Version : 12.0.0.0 
//
//      Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//      le code est régénéré.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TDD.UI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Search - Utilisez 'SearchParams' pour passer les paramètres dans cette méthode.
        /// </summary>
        public void Search()
        {
            #region Variable Declarations
            WinEdit uISearchTextboxEdit = this.UIForm1Window.UISearchTextboxWindow.UISearchTextboxEdit;
            WinButton uISearchButton = this.UIForm1Window.UISearchWindow.UISearchButton;
            #endregion

            // Taper 'tdd' dans 'searchTextbox' zone de texte
            uISearchTextboxEdit.Text = this.SearchParams.UISearchTextboxEditText;

            // Clic 'Search' bouton
            Mouse.Click(uISearchButton, new Point(24, 5));
        }
        
        /// <summary>
        /// BookIdAssert - Utilisez 'BookIdAssertExpectedValues' pour passer les paramètres dans cette méthode.
        /// </summary>
        public void BookIdAssert()
        {
            #region Variable Declarations
            WinCell uIItem23Cell = this.UIForm1Window.UIMainGridViewWindow.UIDataGridViewTable.UILigne0Row.UIItem23Cell;
            #endregion

            // Vérifier que la propriété 'Value' de '23' cellule est égal à '23'
            Assert.AreEqual(this.BookIdAssertExpectedValues.UIItem23CellValue, uIItem23Cell.Value);
        }
        
        #region Properties
        public virtual SearchParams SearchParams
        {
            get
            {
                if ((this.mSearchParams == null))
                {
                    this.mSearchParams = new SearchParams();
                }
                return this.mSearchParams;
            }
        }
        
        public virtual BookIdAssertExpectedValues BookIdAssertExpectedValues
        {
            get
            {
                if ((this.mBookIdAssertExpectedValues == null))
                {
                    this.mBookIdAssertExpectedValues = new BookIdAssertExpectedValues();
                }
                return this.mBookIdAssertExpectedValues;
            }
        }
        
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        #endregion
        
        #region Fields
        private SearchParams mSearchParams;
        
        private BookIdAssertExpectedValues mBookIdAssertExpectedValues;
        
        private UIForm1Window mUIForm1Window;
        #endregion
    }
    
    /// <summary>
    /// Paramètres à passer dans 'Search'
    /// </summary>
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public class SearchParams
    {
        
        #region Fields
        /// <summary>
        /// Taper 'tdd' dans 'searchTextbox' zone de texte
        /// </summary>
        public string UISearchTextboxEditText = "tdd";
        #endregion
    }
    
    /// <summary>
    /// Paramètres à passer dans 'BookIdAssert'
    /// </summary>
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public class BookIdAssertExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Vérifier que la propriété 'Value' de '23' cellule est égal à '23'
        /// </summary>
        public string UIItem23CellValue = "23";
        #endregion
    }
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Critères de recherche 
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UISearchTextboxWindow UISearchTextboxWindow
        {
            get
            {
                if ((this.mUISearchTextboxWindow == null))
                {
                    this.mUISearchTextboxWindow = new UISearchTextboxWindow(this);
                }
                return this.mUISearchTextboxWindow;
            }
        }
        
        public UISearchWindow UISearchWindow
        {
            get
            {
                if ((this.mUISearchWindow == null))
                {
                    this.mUISearchWindow = new UISearchWindow(this);
                }
                return this.mUISearchWindow;
            }
        }
        
        public UIMainGridViewWindow UIMainGridViewWindow
        {
            get
            {
                if ((this.mUIMainGridViewWindow == null))
                {
                    this.mUIMainGridViewWindow = new UIMainGridViewWindow(this);
                }
                return this.mUIMainGridViewWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISearchTextboxWindow mUISearchTextboxWindow;
        
        private UISearchWindow mUISearchWindow;
        
        private UIMainGridViewWindow mUIMainGridViewWindow;
        #endregion
    }
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public class UISearchTextboxWindow : WinWindow
    {
        
        public UISearchTextboxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Critères de recherche 
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "searchTextbox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UISearchTextboxEdit
        {
            get
            {
                if ((this.mUISearchTextboxEdit == null))
                {
                    this.mUISearchTextboxEdit = new WinEdit(this);
                    #region Critères de recherche 
                    this.mUISearchTextboxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUISearchTextboxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUISearchTextboxEdit;
        #endregion
    }
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public class UISearchWindow : WinWindow
    {
        
        public UISearchWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Critères de recherche 
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "searchButton";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UISearchButton
        {
            get
            {
                if ((this.mUISearchButton == null))
                {
                    this.mUISearchButton = new WinButton(this);
                    #region Critères de recherche 
                    this.mUISearchButton.SearchProperties[WinButton.PropertyNames.Name] = "Search";
                    this.mUISearchButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUISearchButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISearchButton;
        #endregion
    }
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public class UIMainGridViewWindow : WinWindow
    {
        
        public UIMainGridViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Critères de recherche 
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "mainGridView";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Critères de recherche 
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UILigne0Row UILigne0Row
        {
            get
            {
                if ((this.mUILigne0Row == null))
                {
                    this.mUILigne0Row = new UILigne0Row(this);
                }
                return this.mUILigne0Row;
            }
        }
        #endregion
        
        #region Fields
        private UILigne0Row mUILigne0Row;
        #endregion
    }
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.21005.1")]
    public class UILigne0Row : WinRow
    {
        
        public UILigne0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Critères de recherche 
            this.SearchProperties[WinRow.PropertyNames.Value] = "TDD.Services.Library.TransportObjects.BookTO;23;TDD with Unity and Moq;(null);(nu" +
                "ll)";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinCell UIItem23Cell
        {
            get
            {
                if ((this.mUIItem23Cell == null))
                {
                    this.mUIItem23Cell = new WinCell(this);
                    #region Critères de recherche 
                    this.mUIItem23Cell.SearchProperties[WinCell.PropertyNames.Value] = "23";
                    this.mUIItem23Cell.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem23Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIItem23Cell;
        #endregion
    }
}
